### ISSUE TITLE
Impossible Seed?

### ISSUE THREAD

**Issue by JusttDandy** [AaronDobbe/wl3-randomizer#3]
I think I found an impossible seed in the randomizer. 
I hope I'm wrong.

Four open accessible levels, the only accessible exits are in the Castle of Illusions, but the only possible key locations require high jump, golden glove, or the Super Overalls to get to. 

Seed: 2CHNeDLBIVy

I've attached my save file and the game file if it helps. 

[file removed]

**Comment by AaronDobbe** [comment]
Hello! I have to ask that you please do not upload ROM files, even those that have been randomized - they are not legal to share. There's a reason the randomizer does not include the original game! Just the seed and your settings are enough for me to recreate your randomized game and check it out. Please let me know the settings you generated the game with (future releases will make this easier) and also confirm what version of the randomizer you are using. Thank you!

**Comment by JusttDandy** [comment]
Oops! Sorry!
I'm using v0.10.2 of the Randomizer

The settings I turned on for the seed were:
Shuffle World Map
Shuffle Key/Coin Locations
Randomize Enemy Colors
Skip Cutscenes

**Comment by AaronDobbe** [comment]
Alright, thank you! I've checked out your seed and played it until I found the golden glove, so I believe I've gotten past where you're stuck. It's definitely a bit of a maze, but key shuffle seeds tend to be that way ^^; It also involves probably the trickiest key location in the game, something that I've already decided I'm removing from the logic next release, until "Hard Mode" is ready.

Here's the path through the seed until the gold glove:

1. W1 Desert Ruins - Red Chest: Torch
2. W4 A Town in Chaos - Gray Chest: Red Glove
3. W4 A Town in Chaos - Blue Chest: Super Flippers
4. W3 The Pool of Rain - Green Chest: Blue Overalls
5. W3 The Pool of Rain - Gray Chest: Spiked Helmet
6. W4 A Town in Chaos - Red Chest: Mirror
7. E3 Castle of Illusions - Green Chest: Wire Wizard
8. S3 Tower of Revival - Green Chest: Beanstalk Seeds
9. W3 The Pool of Rain - Red Chest: Gold Glove

Step 7 is the tricky part. I've recorded a video of how to get the green key; it must be done at daytime. [Here's a link.](https://www.youtube.com/watch?v=6IawNsYcN5E) If you're having trouble with the Hammerbot, look to see how much of Wario's hand is still visible after getting hit; if you can see more than a few pixels of his hand after getting hit, you weren't standing far enough left.

I hope this helps! I do want to apologize for the Hammerbot trick; as part of adjusting the game balance, I've added and removed certain tricks according to feedback. This was recently discovered, and I decided to add it because it's not very hard; however, the combination of it being just a little precise and rather obscure means it has tripped up almost everyone who came across it. :( I'm working on the next version and, once it's available, the trick will either be removed from the logic, or exclusive to Hard Mode if I have that ready by then.

**Comment by JusttDandy** [comment]
AHHHH Thank you!

I tried something similar to that earlier, but started Wario much further right in the doorway, and honestly thought there was an invisible wall preventing me from passing until the effect wore off. 

Thank you so much for your time and detailed explanation, and I look forward to Hard Mode!!
